name: KChallengesNew
version: '1.1.0'
main: yt.lost.kChallengesNew.KChallengesNew
api-version: '1.21'
commands:
  challenge:
    description: challenges
  backpack:
    aliases:
      - bp
  result:
    description: reveal result
    aliases:
      - reveal